/** @type {import('@commitlint/types').UserConfig} */
module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'style',
        'refactor',
        'perf',
        'test',
        'build',
        'ci',
        'chore',
        'revert',
        'infra',
      ],
    ],
    'scope-enum': [
      1,
      'always',
      [
        'auth',
        'user',
        'career',
        'exam',
        'ai',
        'org',
        'billing',
        'notification',
        'admin',
        'analytics',
        'gateway',
        'common',
        'config',
        'logger',
        'database',
        'events',
        'types',
        'utils',
        'validation',
        'errors',
        'infra',
        'ci',
        'docs',
        'deps',
      ],
    ],
    'subject-case': [2, 'never', ['sentence-case', 'start-case', 'pascal-case', 'upper-case']],
    'header-max-length': [2, 'always', 100],
    'body-max-line-length': [1, 'always', 200],
  },
};
